// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class BillDetailes
    {
        public int BillDetailesId { get; set; }
        public int BillMasterId { get; set; }
        public int CategoryId { get; set; }
        public int Quantity { get; set; }
        public float QuantityPrice { get; set; }

        public virtual BillsMaster BillMaster { get; set; }
        public virtual Categories Category { get; set; }
    }
}