// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class BillsMaster
    {
        public BillsMaster()
        {
            BillDetailes = new HashSet<BillDetailes>();
        }

        public int BillMasterId { get; set; }
        public int IdUser { get; set; }
        public int CustomerId { get; set; }
        public DateTime Date { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<BillDetailes> BillDetailes { get; set; }
    }
}