// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Categories
    {
        public Categories()
        {
            BillDetailes = new HashSet<BillDetailes>();
            StoreCategoryCredits = new HashSet<StoreCategoryCredits>();
        }

        public int CategoryId { get; set; }
        public int IdUser { get; set; }
        public string NameCategory { get; set; }
        public float? PriceCategory { get; set; }
        public int IdCoin { get; set; }

        public virtual Coin IdCoinNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<BillDetailes> BillDetailes { get; set; }
        public virtual ICollection<StoreCategoryCredits> StoreCategoryCredits { get; set; }
    }
}