// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Coin
    {
        public Coin()
        {
            Categories = new HashSet<Categories>();
            CustomerCredits = new HashSet<CustomerCredits>();
        }

        public int CoinId { get; set; }
        public string NameCoin { get; set; }
        public int UserId { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<CustomerCredits> CustomerCredits { get; set; }
    }
}