// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Customer
    {
        public Customer()
        {
            BillsMaster = new HashSet<BillsMaster>();
            CustomerCredits = new HashSet<CustomerCredits>();
        }

        public int CustomerId { get; set; }
        public int? UserId { get; set; }
        public string CustmerName { get; set; }
        public string CustomerAddress { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<BillsMaster> BillsMaster { get; set; }
        public virtual ICollection<CustomerCredits> CustomerCredits { get; set; }
    }
}