// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class CustomerCredits
    {
        public int CustomerCredeitId { get; set; }
        public int IdCoin { get; set; }
        public int CustomerId { get; set; }
        public float? Balance { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Coin IdCoinNavigation { get; set; }
    }
}