// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class OrderMaster
    {
        public OrderMaster()
        {
            OrderDetailes = new HashSet<OrderDetailes>();
        }

        public int OrderMasterId { get; set; }
        public int IdUser { get; set; }
        public DateTime OrderDate { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<OrderDetailes> OrderDetailes { get; set; }
    }
}