// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class OrderDetailes
    {
        public int OrderDetailesId { get; set; }
        public int OrderMasterId { get; set; }
        public int RawMaterialId { get; set; }
        public int Quantity { get; set; }
        public float QuantityPrice { get; set; }

        public virtual OrderMaster OrderMaster { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
    }
}