// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class RawMaterial
    {
        public RawMaterial()
        {
            OrderDetailes = new HashSet<OrderDetailes>();
            StoreRawCredits = new HashSet<StoreRawCredits>();
        }

        public int RawMaterialId { get; set; }
        public int IdUser { get; set; }
        public string NameRawMaterial { get; set; }
        public float? PriceRawMaterial { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<OrderDetailes> OrderDetailes { get; set; }
        public virtual ICollection<StoreRawCredits> StoreRawCredits { get; set; }
    }
}