// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class StoreCategoryCredits
    {
        public int StoreCredeitId { get; set; }
        public int IdUser { get; set; }
        public int StoreId { get; set; }
        public int CategoryId { get; set; }
        public int StoreQuantity { get; set; }

        public virtual Categories Category { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual Stores Store { get; set; }
    }
}