// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class StoreRawCredits
    {
        public int StoreRawCredeitId { get; set; }
        public int IdUser { get; set; }
        public int StoreId { get; set; }
        public int RawMaterialId { get; set; }
        public int StoreQuantity { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual Stores Store { get; set; }
    }
}