// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Stores
    {
        public Stores()
        {
            StoreCategoryCredits = new HashSet<StoreCategoryCredits>();
            StoreRawCredits = new HashSet<StoreRawCredits>();
        }

        public int StoreId { get; set; }
        public int IdUser { get; set; }
        public string StoreLocacion { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<StoreCategoryCredits> StoreCategoryCredits { get; set; }
        public virtual ICollection<StoreRawCredits> StoreRawCredits { get; set; }
    }
}