// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class UserPrivileges
    {
        public int IdUserPrivilege { get; set; }
        public int PrivilegeId { get; set; }
        public int UserId { get; set; }

        public virtual Privileges Privilege { get; set; }
        public virtual Users User { get; set; }
    }
}