// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi
{
    public partial class Users
    {
        public Users()
        {
            BillsMaster = new HashSet<BillsMaster>();
            Categories = new HashSet<Categories>();
            Coin = new HashSet<Coin>();
            Customer = new HashSet<Customer>();
            OrderMaster = new HashSet<OrderMaster>();
            Privileges = new HashSet<Privileges>();
            RawMaterial = new HashSet<RawMaterial>();
            StoreCategoryCredits = new HashSet<StoreCategoryCredits>();
            StoreRawCredits = new HashSet<StoreRawCredits>();
            Stores = new HashSet<Stores>();
            UserPrivileges = new HashSet<UserPrivileges>();
        }

        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<BillsMaster> BillsMaster { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Coin> Coin { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<OrderMaster> OrderMaster { get; set; }
        public virtual ICollection<Privileges> Privileges { get; set; }
        public virtual ICollection<RawMaterial> RawMaterial { get; set; }
        public virtual ICollection<StoreCategoryCredits> StoreCategoryCredits { get; set; }
        public virtual ICollection<StoreRawCredits> StoreRawCredits { get; set; }
        public virtual ICollection<Stores> Stores { get; set; }
        public virtual ICollection<UserPrivileges> UserPrivileges { get; set; }
    }
}